import type { AdminBookingDetail } from "@/lib/admin/bookings/types";
import { prisma } from "@/lib/prisma";

function decimalToNumber(value: { toNumber: () => number } | null | undefined): number | null {
  return value ? value.toNumber() : null;
}

export async function getAdminBookingById(id: string): Promise<AdminBookingDetail | null> {
  const booking = await prisma.booking.findUnique({
    where: { id },
    select: {
      id: true,
      bookingReference: true,
      status: true,
      createdAt: true,
      updatedAt: true,
      customerFullName: true,
      customerPhone: true,
      customerEmail: true,
      customerNationality: true,
      customerDateOfBirth: true,
      customerLicenseCategory: true,
      customerSpecialNotes: true,
      customerLicenseUploadPath: true,
      customerPassportUploadPath: true,
      customerWillPresentLicenseAtPickup: true,
      customerWillPresentIdAtPickup: true,
      vehicleId: true,
      vehicleNameSnapshot: true,
      vehicleLicensePlateSnapshot: true,
      vehicleType: true,
      vehicleTypeSnapshot: true,
      pickupDateTime: true,
      returnDateTime: true,
      billableDays: true,
      actualDurationHours: true,
      pickupOption: true,
      pickupAddress: true,
      pickupLatitude: true,
      pickupLongitude: true,
      dropoffOption: true,
      dropoffAddress: true,
      dropoffLatitude: true,
      dropoffLongitude: true,
      cdwOption: true,
      cdwDailyRate: true,
      cdwTotal: true,
      helmetSize1: true,
      helmetSize2: true,
      storageBoxSelected: true,
      storageBoxCost: true,
      additionalDriverEnabled: true,
      additionalDriverFullName: true,
      additionalDriverPhone: true,
      additionalDriverEmail: true,
      additionalDriverNationality: true,
      additionalDriverDateOfBirth: true,
      additionalDriverLicenseCategory: true,
      additionalDriverLicenseUploadPath: true,
      additionalDriverPassportUploadPath: true,
      additionalDriverWillPresentLicenseAtPickup: true,
      additionalDriverWillPresentIdAtPickup: true,
      additionalDriverDailyRate: true,
      additionalDriverTotal: true,
      baseDailyRateSnapshot: true,
      durationDiscountPercentSnapshot: true,
      appliedDailyRateSnapshot: true,
      rentalCost: true,
      hotelCodeSnapshot: true,
      hotelPartnerNameSnapshot: true,
      hotelDiscountPercentSnapshot: true,
      hotelDiscountAmountSnapshot: true,
      subtotalAfterHotelDiscountSnapshot: true,
      deliveryFee: true,
      dropoffFee: true,
      deliveryTotal: true,
      subtotal: true,
      depositAmount: true,
      depositMethod: true,
      totalDueOnline: true,
      totalDueLater: true,
      termsAccepted: true,
      termsAcceptedAt: true,
      termsVersion: true,
      consentSource: true,
      confirmationEmailStatus: true,
      confirmationEmailSentAt: true,
      statusHistory: {
        orderBy: { createdAt: "desc" },
        select: {
          id: true,
          oldStatus: true,
          newStatus: true,
          note: true,
          createdAt: true,
          changedBy: {
            select: { name: true },
          },
        },
      },
    },
  });

  if (!booking) {
    return null;
  }

  return {
    id: booking.id,
    bookingReference: booking.bookingReference,
    status: booking.status,
    createdAt: booking.createdAt.toISOString(),
    updatedAt: booking.updatedAt.toISOString(),
    customerFullName: booking.customerFullName,
    customerPhone: booking.customerPhone,
    customerEmail: booking.customerEmail,
    customerNationality: booking.customerNationality,
    customerDateOfBirth: booking.customerDateOfBirth.toISOString(),
    customerLicenseCategory: booking.customerLicenseCategory,
    customerSpecialNotes: booking.customerSpecialNotes,
    customerLicenseUploadPath: booking.customerLicenseUploadPath,
    customerPassportUploadPath: booking.customerPassportUploadPath,
    customerWillPresentLicenseAtPickup: booking.customerWillPresentLicenseAtPickup,
    customerWillPresentIdAtPickup: booking.customerWillPresentIdAtPickup,
    vehicleId: booking.vehicleId,
    vehicleName: booking.vehicleNameSnapshot ?? "—",
    vehicleLicensePlate: booking.vehicleLicensePlateSnapshot,
    vehicleType: booking.vehicleType,
    vehicleTypeSnapshot: booking.vehicleTypeSnapshot,
    pickupDateTime: booking.pickupDateTime.toISOString(),
    returnDateTime: booking.returnDateTime.toISOString(),
    billableDays: booking.billableDays,
    actualDurationHours: booking.actualDurationHours.toNumber(),
    pickupOption: booking.pickupOption,
    pickupAddress: booking.pickupAddress,
    pickupLatitude: decimalToNumber(booking.pickupLatitude),
    pickupLongitude: decimalToNumber(booking.pickupLongitude),
    dropoffOption: booking.dropoffOption,
    dropoffAddress: booking.dropoffAddress,
    dropoffLatitude: decimalToNumber(booking.dropoffLatitude),
    dropoffLongitude: decimalToNumber(booking.dropoffLongitude),
    cdwOption: booking.cdwOption,
    cdwDailyRate: booking.cdwDailyRate.toNumber(),
    cdwTotal: booking.cdwTotal.toNumber(),
    helmetSize1: booking.helmetSize1,
    helmetSize2: booking.helmetSize2,
    storageBoxSelected: booking.storageBoxSelected,
    storageBoxCost: booking.storageBoxCost.toNumber(),
    additionalDriverEnabled: booking.additionalDriverEnabled,
    additionalDriverFullName: booking.additionalDriverFullName,
    additionalDriverPhone: booking.additionalDriverPhone,
    additionalDriverEmail: booking.additionalDriverEmail,
    additionalDriverNationality: booking.additionalDriverNationality,
    additionalDriverDateOfBirth: booking.additionalDriverDateOfBirth?.toISOString() ?? null,
    additionalDriverLicenseCategory: booking.additionalDriverLicenseCategory,
    additionalDriverLicenseUploadPath: booking.additionalDriverLicenseUploadPath,
    additionalDriverPassportUploadPath: booking.additionalDriverPassportUploadPath,
    additionalDriverWillPresentLicenseAtPickup: booking.additionalDriverWillPresentLicenseAtPickup,
    additionalDriverWillPresentIdAtPickup: booking.additionalDriverWillPresentIdAtPickup,
    additionalDriverDailyRate: booking.additionalDriverDailyRate.toNumber(),
    additionalDriverTotal: booking.additionalDriverTotal.toNumber(),
    baseDailyRateSnapshot: decimalToNumber(booking.baseDailyRateSnapshot),
    durationDiscountPercentSnapshot: decimalToNumber(booking.durationDiscountPercentSnapshot),
    appliedDailyRateSnapshot: decimalToNumber(booking.appliedDailyRateSnapshot),
    rentalCost: booking.rentalCost.toNumber(),
    hotelCode: booking.hotelCodeSnapshot,
    hotelName: booking.hotelPartnerNameSnapshot,
    hotelDiscountPercentSnapshot: decimalToNumber(booking.hotelDiscountPercentSnapshot),
    hotelDiscountAmountSnapshot: decimalToNumber(booking.hotelDiscountAmountSnapshot),
    subtotalAfterHotelDiscountSnapshot: decimalToNumber(booking.subtotalAfterHotelDiscountSnapshot),
    deliveryFee: booking.deliveryFee.toNumber(),
    dropoffFee: booking.dropoffFee.toNumber(),
    deliveryTotal: booking.deliveryTotal.toNumber(),
    subtotal: booking.subtotal.toNumber(),
    depositAmount: booking.depositAmount.toNumber(),
    depositMethod: booking.depositMethod,
    totalDueOnline: booking.totalDueOnline.toNumber(),
    totalDueLater: booking.totalDueLater.toNumber(),
    termsAccepted: booking.termsAccepted,
    termsAcceptedAt: booking.termsAcceptedAt?.toISOString() ?? null,
    termsVersion: booking.termsVersion,
    consentSource: booking.consentSource,
    confirmationEmailStatus: booking.confirmationEmailStatus,
    confirmationEmailSentAt: booking.confirmationEmailSentAt?.toISOString() ?? null,
    statusHistory: booking.statusHistory.map((entry) => ({
      id: entry.id,
      oldStatus: entry.oldStatus,
      newStatus: entry.newStatus,
      note: entry.note,
      changedByAdminName: entry.changedBy?.name ?? null,
      createdAt: entry.createdAt.toISOString(),
    })),
  };
}
